- lua/lib/tweak_data/charactertweakdata.lua
Set death vox cloaker health to 960, headshot multiplier to 3.
> cloaker health/headshot set

- lua/lib/tweak_data/groupaitweakdata.lua
resolved std_5 group error, fixed rate of st_1 spawn during assault.
> resolve group bugs

- lua/lib/tweak_data/groupaitweakdata.lua
tactics generated, tactics applied to all death vox units.
> First tactics pass

- lua/lib/tweak_data/charactertweakdata.lua
Guards have easy surrender preset.
> Guards now surrender.

- lua/lib/units/beings/player/states/playertased.lua
We need to see if this helps or hurts the situation. I think the shake effect is potentially the culprit for flashing screen.
> reduced shake effect, increased rate.

- lua/lib/units/beings/player/states/playertased.lua
> Intensifying taser effect

- lua/lib/tweak_data/groupaitweakdata.lua
Should improve police aggression, reduce likelihood of pathing issues.
Also fixed typos in vanilla tactics (though this should do nothing)
> Tactics revision pass

- lua/lib/units/beings/player/states/playertased.lua
You will definitely need to check my math on this one. I believe I have the difficulty conditionals set right, at least
> Experimental taser recoil adjustment

- lua/lib/tweak_data/charactertweakdata.lua
Many of these are adjustments to formatting to ease future revision.
Others are increases in resistance, health, damage, or falloff in response to calls for greater challenge. 
Some may need to be tweaked back down based on feedback, but the game should be much less easy to solo with these.
> Surprise: Merry Xmas, revised tweakdata.

- lua/lib/tweak_data/weapontweakdata.lua
smg weapons adjusted up to 45 base damage.
> Xmas smg damage revisions

- lua/lib/tweak_data/charactertweakdata.lua
Corrected multiple errors to enemy surrender chance, synced sniper health, made ninja dodge preset nastier, gave it to light swat, and increased explosive damage resistance.
> Mutliple cleanups

- lua/lib/units/enemies/medic/medicdamage.lua
Not certain I've implemented the cooldown properly- I can't find where the vanilla time (3 seconds) is set.
> Attempted reduced cooldown and removal of immunities.

- lua/lib/tweak_data/groupaitweakdata.lua
I've fixed some typos, adjusted some balances. I've re-added aegeas to the multiplayer spawngroup set, but don't worry- it's got tasers instead of grenadiers. I needed a group there to even out some of the other spawn probability math.
I may follow up down the line with adjustments o the reenforce groups.
> Multiple rebalances/corrections

- lua/lib/tweak_data/weapontweakdata.lua
greendozer damage increase and saiga ammo increase, preparatory for falloff and other stat adjustment.
Saigadozers basically getting the big brother mag.
> small dozer changes

- lua/lib/tweak_data/charactertweakdata.lua
I do need to look up how this is initialized, but I believe this will help.
> deathguard correction on shields

- lua/lib/tweak_data/charactertweakdata.lua
Adding hp settings for some enemies, preparing chavez's dodge and weapon preset. All require scrutiny. Also did slight reorg of some lines so I can tell what I'm doing.
> Chavez prep, hp gaps

- lua/lib/managers/mission/elementspawnenemydummy.lua
Still far from complete, but gives scale and documentation. While we may not actually use this replace method for all of these enemies, this file also serves as a repository for their paths and roles, where necessary.
> General enemy framework/documentation

- lua/lib/tweak_data/groupaitweakdata.lua
I think this actually fixes most of the currently reported balance issues.
> Reduce dozer cap to 2

- lua/lib/tweak_data/charactertweakdata.lua
changes so they don't break windows, etc
> fix for guard access

- lua/lib/units/enemies/cop/copdamage.lua
marginally cleaner body expertise check, belt and suspenders with other change.
> cleaner body expertise check

- assets/units/pd2_mod_gageammo/characters/ene_deathvox_gman_noflashlight/ene_deathvox_gman_noflashlight.object
removes specular from no flashlight variant of gman.
> gman nolight variant flashlight fix

- lua/lib/tweak_data/charactertweakdata.lua
Might make them more effective. Horribly, horribly untested.
> Custom shield speed preset change

- map_replacements/Bank_cash_CD/changelog.txt
- map_replacements/Bank_cash_CD/levels/branchbank_cash_CD/world/world.mission
Testing merged file upload method for heist fixing.
> bank cash fix upload test

- hooks.xml
- lua/lib/tweak_data/charactertweakdata.lua
- lua/lib/tweak_data/levelstweakdata.lua
- lua/lib/tweak_data/weapontweakdata.lua
- map_replacements/Bank_cash_CD/changelog.txt
- map_replacements/Bank_cash_CD/levels/branchbank_cash_CD/world/world.mission
General upward revision and tier implementation on basic units, based on initial tests with starting inventory. Does not change upper difficulties; primary focus is first three difficulties.
> HP value mk 2

- hooks.xml
- lua/lib/units/enemies/spooc/actions/lower_body/actionspooc.lua
commenting out one lua from hook (will re-add viable optimizations when able) and removing associated cloaker charge optimization dependency.
> fix for FSS-induced enemy pathing behavior issues

- map_replacements/Aftershock_CD/loc/english.txt
- map_replacements/Transport Crossroads Crackdown/loc/english.txt
- map_replacements/Transport Underpass Crackdown/loc/english.txt
annotating loc files for heists that will not function below CD.
> Diff-limited heist annotations

- lua/lib/units/enemies/taser/logics/taserlogicattack.lua
Possibly fixes tasers letting go too much of players, submitted here since that's where my fwd_dot fix went to as well.
> under_multiple_fire change

- assets/units/pd2_mod_gageammo/characters/ene_deathvox_taser/ene_deathvox_taser.unit
- assets/units/pd2_mod_gageammo/characters/ene_deathvox_taser/ene_deathvox_taser_husk.unit
- lua/lib/tweak_data/charactertweakdata.lua
- lua/lib/tweak_data/weapontweakdata.lua
Initial structure for next round of unit edits for heist-specific enemies.
> Setting up scripted unit stat corrections

- lua/lib/units/enemies/taser/logics/taserlogicattack.lua
forgot to remove this little line
> billionth taser fix

- lua/lib/tweak_data/charactertweakdata.lua
- lua/lib/units/enemies/cop/copdamage.lua
Fixes explosive crash bug and implements additional taser targeting fix.
> May 2019 Hotfix

- lua/lib/managers/group_ai_states/groupaistatebesiege.lua
As asked by Vox, here they are.
> New escalation features.

- hooks.xml
- lua/lib/managers/group_ai_states/groupaistatebesiege.lua
- lua/lib/managers/skirmishmanager
- lua/lib/tweak_data/levelstweakdata.lua
- lua/lib/tweak_data/skirmishtweakdata.lua
Includes: Fix for enemy retreats in Holdout, test values for duration in order to make testing easier, implementation of Difficulty Go UP, and commenting out stuff that just crashes the game
> holdout difficulty scale test 

- lua/lib/managers/group_ai_states/groupaistatebesiege.lua
- lua/lib/tweak_data/groupaitweakdata.lua
Use GroupAITweakData's numbers at the end to adjust active enemy force per-wave.
>  holdout enemy count per-wave structure

- lua/lib/units/enemies/cop/copbrain.lua
there was an unescessary end in the file that was causing everything to break
> fixed copbrain.lua crash

- lua/lib/managers/group_ai_states/groupaistatebesiege.lua
- lua/lib/tweak_data/groupaitweakdata.lua
they're currently set according to vox-workspace on discord, changeable through groupaitweakdata
>  Holdout killcount force pool structure

- lua/lib/managers/group_ai_states/groupaistatebesiege.lua
- lua/lib/managers/menumanager.lua
- lua/lib/tweak_data/groupaitweakdata.lua
- lua/lib/tweak_data/levelstweakdata.lua
- Made holdout actually start on normal on contract buy
- Fixed min_enemies_left being too high which caused assault waves to end too soon.
- Added classic enemies spawning into holdout
> holdout commit #255

- lua/lib/units/weapons/dvgrenade.lua
- lua/lib/units/weapons/quickcsgrenade.lua
Fixes the Grenadier crashing the game upon firing.
> Grenadier Crash Fix

- damagesyncing
- supermod.xml
bro, you just posted hoxicode, you are going to gain players
> damage networking xmltweak for hoxi's code

- lua/lib/managers/playermanager.lua
- lua/lib/tweak_data/skilltreetweakdata.lua
- lua/lib/tweak_data/upgradestweakdata.lua
- lua/lib/units/beings/player/playerdamage.lua
- lua/loc/loc.lua
- Added the TCD rework of the Anarchist perkdeck!
- Fixed Ex-President's Approval meter showing up when it's not equipped
> Punk means thinking for yerself!

- hooks.xml
- lua/lib/managers/menumanager.lua
- lua/lib/managers/usermanager.lua
- lua/lib/units/beings/player/states/playerstandard.lua
- lua/lib/units/cameras/fpcameraplayerbase.lua
- lua/loc/loc.lua
This update, courtesy of fuglore, adds the following menu options (both are off by default):
- Static recoil patterns
- Hold-to-fire for singlefire weapons
> Small accessibility update

- lua/lib/units/beings/player/states/playerstandard.lua
Small crash fix to skill-related player movement code
> fixed a crash in playerstandard

- lua/lib/units/weapons/raycastweaponbase.lua
Last minute addition fixing Special Toys skill.
> Special Toys Aced fix

- coredeathvox.lua
- hooks.xml
- loc/tcd_en.txt
- lua/lib/managers/blackmarketmanager.lua
- lua/lib/managers/playermanager.lua
- lua/lib/network/handlers/unitnetworkhandler.lua
- lua/lib/network/matchmaking/networkmatchmakingepic.lua
- lua/lib/tweak_data/blackmarket/projectilestweakdata.lua
- lua/lib/tweak_data/equipmentstweakdata.lua
- lua/lib/tweak_data/skilltreetweakdata.lua
- lua/lib/tweak_data/upgradestweakdata.lua
- lua/lib/units/beings/player/playerdamage.lua
- lua/lib/units/beings/player/playerequipment.lua
- lua/lib/units/beings/player/states/playerstandard.lua
- lua/lib/units/contourext.lua
- lua/lib/units/enemies/boss/logics/bosslogicattack.lua
- lua/lib/units/enemies/cop/copdamage.lua
- lua/lib/units/equipment/sentry_gun/sentrygundamage.lua
- lua/lib/units/weapons/raycastweaponbase.lua
- lua/lib/units/weapons/shotgunbase.lua
Fixed crashing upon being tased
Fixed crashing upon hitting held shield objects
Increased max cable ties count to 20
Perk deck throwables overhauled: throwables from perk decks (Kingpin, Sicario, Hacker, Stoic, Tag Team Leech)
Note: of the perk decks that have gadgets, only Tag Team is implemented at the moment. The others are currently in progress and will be released soon.
The perk decks are also undergoing implementation of another balance pass 
Crew Chief and Muscle perk decks buffed
Fixed numerous crashes from U237 through U238.1 (current patch as of writing this)
> July 1 2023
